/**
 * Journey: existingUser creates a site with autogenerated URLs.
 *
 * `docs/acceptance-testing-workplan.md` carries the steps. With custom page keys
 * off, `createSite` adds the document without a key of its own and takes the one
 * Firestore generates, so the address the reader lands on cannot be read out of
 * the name they typed.
 */
import type { Browser, Page } from 'playwright';
import { t } from 'src/utils/i18n';
import { toMekanismiURI } from 'src/utils/mekanismiUtils';
import { afterAll, beforeAll, expect, it } from 'vitest';
import { openReaderPage, uniqueSiteName } from '../harness';

let browser: Browser;
let page: Page;

beforeAll(async () => {
  ({ browser, page } = await openReaderPage());
});

afterAll(async () => {
  await browser?.close();
});

it('creates a site whose address the name did not produce', async () => {
  const name = uniqueSiteName('autogenerated urls');
  const derivedKey = toMekanismiURI(name);

  // 1. Open the options and switch custom page keys off.
  await page.goto('/create/site');
  const nameField = page.locator('form input[name="name"]');
  await nameField.waitFor({ state: 'visible' });

  await page.getByRole('switch', { name: t('actions:show.options') }).check();
  await page
    .getByRole('switch', { name: t('entries:site.customPageKeys') })
    .uncheck();

  // 2. Name the site. The address preview stands where the derived key would
  // otherwise be, and says the address is generated instead.
  await nameField.fill(name);
  await nameField.blur();

  const address = page.locator('form code');
  await expect
    .poll(() => address.textContent(), { timeout: 15_000 })
    .toContain('[auto]');
  expect(await address.textContent()).not.toContain(derivedKey);

  // 3. Submit, and land at an address the name did not produce.
  await page.locator('form button[type="submit"]').click();
  await page.waitForURL(/\/sites\/[^/]+$/);

  const landedKey = new URL(page.url()).pathname.split('/').pop();
  expect(landedKey).not.toBe(derivedKey);

  const frontPageHeading = page
    .locator('article.surface')
    .getByRole('heading', { name, level: 1 });
  await expect
    .poll(() => frontPageHeading.isVisible(), { timeout: 30_000 })
    .toBe(true);
});
