#!/usr/bin/env bash
# run.sh — headless persona QA runner.
#
# Composes harness.md + a persona file into one prompt, runs it through the
# Antigravity CLI (agy) in print mode with a structured-output schema, and
# writes the report to docs/reports/YYYY-MM-DD-qa-<persona>.md.
#
# Usage: agents/qa/run.sh [all|<persona> ...] [--model <id>]
set -euo pipefail

QA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$QA_DIR/../.." && pwd)"
REPORTS_DIR="$REPO_ROOT/docs/reports"
BASE_URL="${BASE_URL:-http://localhost:4321}"
PRINT_TIMEOUT="${QA_PRINT_TIMEOUT:-20m}"

model=""
selection=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --model)
      model="$2"
      shift 2
      ;;
    *)
      selection+=("$1")
      shift
      ;;
  esac
done

available=()
for f in "$QA_DIR"/personas/*.md; do
  available+=("$(basename "$f" .md)")
done

personas=("${available[@]}")
if [[ ${#selection[@]} -gt 0 && ! " ${selection[*]} " == *" all "* ]]; then
  personas=("${selection[@]}")
fi

for p in "${personas[@]}"; do
  if [[ ! -f "$QA_DIR/personas/$p.md" ]]; then
    echo "Unknown persona: $p. Available: ${available[*]}, all." >&2
    exit 1
  fi
done

# Start the dev server when nothing answers at BASE_URL; leave a running one alone.
started_pid=""
if ! curl -sf --max-time 5 -o /dev/null "$BASE_URL"; then
  echo "No server at $BASE_URL, starting pelilauta dev..."
  (cd "$REPO_ROOT" && ASTRO_DEV_BACKGROUND=1 pnpm --filter pelilauta dev >/dev/null 2>&1) &
  started_pid=$!
  trap '[[ -n "$started_pid" ]] && kill "$started_pid" 2>/dev/null' EXIT
  for _ in $(seq 1 120); do
    curl -sf --max-time 2 -o /dev/null "$BASE_URL" && break
    sleep 1
  done
  if ! curl -sf --max-time 2 -o /dev/null "$BASE_URL"; then
    echo "Dev server did not answer at $BASE_URL within 120s." >&2
    exit 1
  fi
fi

mkdir -p "$REPORTS_DIR"
date="$(date +%F)"
failures=0
created_content=0

for p in "${personas[@]}"; do
  echo "Running persona: $p..."
  prompt="$(cat "$QA_DIR/harness.md"; echo; cat "$QA_DIR/personas/$p.md")"
  report_path="$REPORTS_DIR/$date-qa-$p.md"

  output="$(agy -p "$prompt" \
    --output-format json \
    --json-schema "$QA_DIR/report-schema.json" \
    --print-timeout "$PRINT_TIMEOUT" \
    --dangerously-skip-permissions \
    ${model:+--model "$model"} 2>&1)" || true

  # The report is either the envelope itself or a JSON string in .response.
  report="$(jq -ce 'if has("narrative") then . else (.response | fromjson) end' \
    <<<"$output" 2>/dev/null)" || report=""

  if [[ -n "$report" ]]; then
    jq -r --arg persona "$p" --arg date "$date" --arg base "$BASE_URL" '
      "# QA persona run: \($persona)\n" +
      "\nGenerated by agents/qa/run.sh on \($date) against \($base).\n" +
      "\n## The visit\n\n\(.narrative)\n" +
      "\n## Impression\n\n\(.impression)\n" +
      "\n## Findings\n\n" +
      (if (.findings | length) == 0 then "No findings."
       else (.findings | map("- **\(.severity)** `\(.route)` — \(.description)") | join("\n"))
       end) +
      (if (.created_content | length) > 0
       then "\n\n## Created content\n\n" +
            (.created_content | map("- \(.)") | join("\n")) +
            "\n\nSweep with `agents/qa/cleanup.sh --apply`."
       else "" end) +
      (if ((.gave_up_on // "") | test("\\S"))
       then "\n\n## Gave up on\n\n" + .gave_up_on
       else "" end) +
      "\n"
    ' <<<"$report" > "$report_path"
    findings="$(jq '.findings | length' <<<"$report")"
    if [[ "$(jq '.created_content | length' <<<"$report")" -gt 0 ]]; then
      created_content=1
    fi
    echo "  $findings finding(s) -> ${report_path#"$REPO_ROOT"/}"
  else
    failures=$((failures + 1))
    {
      echo "# QA persona run: $p"
      echo
      echo "Generated by agents/qa/run.sh on $date against $BASE_URL."
      echo
      echo "## Run failed"
      echo
      echo "The agy run produced no parseable report."
      echo
      echo '```'
      tail -c 4000 <<<"${output:-no output}"
      echo '```'
    } > "$report_path"
    echo "  run failed -> ${report_path#"$REPO_ROOT"/}" >&2
  fi
done

if [[ "$created_content" -eq 1 ]]; then
  echo
  echo "Personas created content in the shared test database. Sweep it with:"
  echo "  agents/qa/cleanup.sh --apply"
fi

exit $((failures > 0 ? 1 : 0))
