/**
 * run.mjs — headless persona QA runner.
 *
 * Composes harness.md + a persona file into one prompt, runs it through the
 * Antigravity CLI (`agy`) in print mode with a structured-output schema, and
 * writes the report to docs/reports/YYYY-MM-DD-qa-<persona>.md.
 *
 * Run: node agents/qa/run.mjs all|<persona> [--model <id>]
 */
import { spawn } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const qaDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(qaDir, '../..');
const personasDir = join(qaDir, 'personas');
const reportsDir = join(repoRoot, 'docs/reports');
const BASE_URL = process.env.BASE_URL || 'http://localhost:4321';
const PRINT_TIMEOUT = process.env.QA_PRINT_TIMEOUT || '20m';

const args = process.argv.slice(2);
const modelIndex = args.indexOf('--model');
const model = modelIndex === -1 ? null : args[modelIndex + 1];
const selection = args.filter(
  (a, i) => modelIndex === -1 || (i !== modelIndex && i !== modelIndex + 1),
);

const available = readdirSync(personasDir)
  .filter((f) => f.endsWith('.md'))
  .map((f) => f.replace(/\.md$/, ''));

const personas =
  selection.length === 0 || selection.includes('all') ? available : selection;

const unknown = personas.filter((p) => !available.includes(p));
if (unknown.length > 0) {
  console.error(
    `Unknown persona(s): ${unknown.join(', ')}. Available: ${available.join(', ')}, all.`,
  );
  process.exit(1);
}

/** Start the dev server when nothing answers at BASE_URL; leave a running one alone. */
async function ensureServer() {
  try {
    const res = await fetch(BASE_URL, { signal: AbortSignal.timeout(5000) });
    if (res.ok) return null;
  } catch {
    // fall through to starting it
  }
  console.log(`No server at ${BASE_URL}, starting pelilauta dev...`);
  const child = spawn('pnpm', ['--filter', 'pelilauta', 'dev'], {
    cwd: repoRoot,
    env: { ...process.env, ASTRO_DEV_BACKGROUND: '1' },
    stdio: 'ignore',
  });
  const deadline = Date.now() + 120_000;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(BASE_URL, { signal: AbortSignal.timeout(2000) });
      if (res.ok) return child;
    } catch {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  child.kill();
  throw new Error(`Dev server did not answer at ${BASE_URL} within 120s.`);
}

function runAgy(prompt) {
  const agyArgs = [
    '-p',
    prompt,
    '--output-format',
    'json',
    '--json-schema',
    join(qaDir, 'report-schema.json'),
    '--print-timeout',
    PRINT_TIMEOUT,
    '--dangerously-skip-permissions',
  ];
  if (model) agyArgs.push('--model', model);
  return new Promise((resolve) => {
    const child = spawn('agy', agyArgs, { cwd: repoRoot });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => {
      stdout += d;
    });
    child.stderr.on('data', (d) => {
      stderr += d;
    });
    child.on('close', (code) => resolve({ code, stdout, stderr }));
    child.on('error', (err) =>
      resolve({ code: -1, stdout, stderr: String(err) }),
    );
  });
}

/**
 * Extract the schema-shaped report from agy's JSON envelope, whose exact shape
 * is not pinned by the CLI: accept the object itself, a nested object, or a
 * JSON string in a result-like field.
 */
function extractReport(stdout) {
  const looksLikeReport = (o) =>
    o && typeof o === 'object' && 'narrative' in o && 'findings' in o;
  let envelope;
  try {
    envelope = JSON.parse(stdout);
  } catch {
    const start = stdout.indexOf('{');
    const end = stdout.lastIndexOf('}');
    if (start === -1 || end <= start) return null;
    try {
      envelope = JSON.parse(stdout.slice(start, end + 1));
    } catch {
      return null;
    }
  }
  if (looksLikeReport(envelope)) return envelope;
  for (const value of Object.values(envelope ?? {})) {
    if (looksLikeReport(value)) return value;
    if (typeof value === 'string') {
      try {
        const parsed = JSON.parse(value);
        if (looksLikeReport(parsed)) return parsed;
      } catch {
        // not JSON, keep looking
      }
    }
  }
  return null;
}

function renderReport(persona, date, report) {
  const lines = [
    `# QA persona run: ${persona}`,
    '',
    `Generated by agents/qa/run.mjs on ${date} against ${BASE_URL}.`,
    '',
    '## The visit',
    '',
    report.narrative.trim(),
    '',
    '## Impression',
    '',
    report.impression.trim(),
    '',
    '## Findings',
    '',
  ];
  if (report.findings.length === 0) {
    lines.push('No findings.');
  } else {
    for (const f of report.findings) {
      lines.push(`- **${f.severity}** \`${f.route}\` — ${f.description}`);
    }
  }
  if (report.created_content.length > 0) {
    lines.push('', '## Created content', '');
    for (const title of report.created_content) {
      lines.push(`- ${title}`);
    }
    lines.push(
      '',
      'Sweep with `node apps/pelilauta/scripts/cleanup-test-db.mjs --apply`.',
    );
  }
  if (report.gave_up_on?.trim()) {
    lines.push('', '## Gave up on', '', report.gave_up_on.trim());
  }
  lines.push('');
  return lines.join('\n');
}

function renderFailure(persona, date, result) {
  return [
    `# QA persona run: ${persona}`,
    '',
    `Generated by agents/qa/run.mjs on ${date} against ${BASE_URL}.`,
    '',
    '## Run failed',
    '',
    `The agy run exited with code ${result.code} and produced no parseable report.`,
    '',
    '```',
    (result.stderr || result.stdout || 'no output').trim().slice(-4000),
    '```',
    '',
  ].join('\n');
}

const startedServer = await ensureServer();
const harness = readFileSync(join(qaDir, 'harness.md'), 'utf8');
const date = new Date().toISOString().slice(0, 10);
mkdirSync(reportsDir, { recursive: true });

let failures = 0;
let createdContent = false;
for (const persona of personas) {
  console.log(`Running persona: ${persona}...`);
  const personaText = readFileSync(join(personasDir, `${persona}.md`), 'utf8');
  const prompt = `${harness}\n\n${personaText}`;
  const result = await runAgy(prompt);
  const report = extractReport(result.stdout);
  const reportPath = join(reportsDir, `${date}-qa-${persona}.md`);
  if (report) {
    writeFileSync(reportPath, renderReport(persona, date, report));
    createdContent ||= report.created_content.length > 0;
    console.log(
      `  ${report.findings.length} finding(s) -> ${reportPath.replace(`${repoRoot}/`, '')}`,
    );
  } else {
    failures += 1;
    writeFileSync(reportPath, renderFailure(persona, date, result));
    console.error(
      `  run failed (exit ${result.code}) -> ${reportPath.replace(`${repoRoot}/`, '')}`,
    );
  }
}

if (createdContent) {
  console.log(
    '\nPersonas created content in the shared test database. Sweep it with:\n' +
      '  node apps/pelilauta/scripts/cleanup-test-db.mjs --apply',
  );
}
if (startedServer) startedServer.kill();
process.exit(failures > 0 ? 1 : 0);
