// @generated by scripts/generate-icon-registry.mjs — DO NOT EDIT

export type CommunityNoun =
  | "add"
  | "arrow-down"
  | "arrow-left"
  | "arrow-up"
  | "card"
  | "chevron-left"
  | "clock"
  | "close"
  | "dots"
  | "drag"
  | "dragger"
  | "fox"
  | "search";

export interface IconEntry {
  inner: string;
  viewBox: string;
}

const _registry: Record<CommunityNoun, IconEntry> = {
  "add": { viewBox: "0 0 128 128", inner: "<polygon\n  fill=\"currentColor\"\n  id=\"icon\"\n  points=\"0,70 8,58 58,58 58,8 70,0 70,58 128,58 120,70 70,70 70,120 58,128 58,70 \"/>" },
  "arrow-down": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\" transform=\"matrix(1,0,0,-1,0.232143,125.879)\">\n        <path d=\"M59.757,9.757L68.243,9.757L96.243,37.757L87.757,46.243C87.757,46.243 77.038,35.523 70,28.485L70,114L58,114L58,28.485L39.778,46.707L31.293,38.222L59.757,9.757Z\"/>\n    </g>" },
  "arrow-left": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\" transform=\"matrix(6.12323e-17,-1,1,6.12323e-17,2.12132,127.768)\">\n        <path d=\"M59.757,9.757L68.243,9.757L96.243,37.757L87.757,46.243C87.757,46.243 77.038,35.523 70,28.485L70,114L58,114L58,28.485L39.778,46.707L31.293,38.222L59.757,9.757Z\"/>\n    </g>" },
  "arrow-up": { viewBox: "0 0 128 128", inner: "<path id=\"icon\" fill=\"currentColor\" d=\"M59.757,9.757L68.243,9.757L96.243,37.757L87.757,46.243C87.757,46.243 77.038,35.523 70,28.485L70,114L58,114L58,28.485L39.778,46.707L31.293,38.222L59.757,9.757Z\"/>" },
  "card": { viewBox: "0 0 128 128", inner: "<path id=\"icon\" fill=\"currentColor\" d=\"M75.1,25l42.8,11.5c3.6,1,6.5,3.3,8.2,6.3c1.8,3,2.4,6.7,1.4,10.3l-16.9,63c-1,3.6-3.3,6.5-6.3,8.2\n\tc-3,1.7-6.7,2.3-10.3,1.4l-42.8-11.5c-3.6-0.9-6.5-3.3-8.2-6.3c-1.2-2-1.8-4.4-1.8-6.9L34,103c-3.6,1-7.3,0.4-10.3-1.4\n\tc-3-1.7-5.4-4.6-6.4-8.2l-16.9-63c-1-3.6-0.4-7.3,1.4-10.3c1.8-3,4.7-5.4,8.2-6.3L52.9,2.2c3.6-1,7.3-0.4,10.3,1.4\n\tc3,1.7,5.4,4.6,6.3,8.2L73,24.6C73.7,24.7,74.4,24.8,75.1,25L75.1,25z M54,6.3L11.2,17.8c-2.5,0.7-4.5,2.3-5.7,4.3\n\tc-1.2,2.1-1.6,4.6-0.9,7.1l16.9,63c0.7,2.5,2.3,4.5,4.3,5.7c2.1,1.2,4.6,1.6,7.1,0.9l42.8-11.5c2.5-0.7,4.5-2.3,5.7-4.3\n\tc1.2-2.1,1.6-4.6,0.9-7.1l-16.9-63c-0.7-2.5-2.3-4.5-4.4-5.7C59,6,56.5,5.6,54,6.3L54,6.3z\"/>" },
  "chevron-left": { viewBox: "0 0 128 128", inner: "<polygon fill=\"currentColor\" id=\"icon\" points=\"80 20 92 32 52 64 92 96 80 108 28 64 80 20\"/>" },
  "clock": { viewBox: "0 0 128 128", inner: "<defs\n     id=\"defs1\" />\n  <g\n     id=\"icon\">\n    <circle\n       style=\"fill:none;stroke-width:7;stroke-linecap:round;paint-order:markers stroke fill;fill-opacity:1;stroke:currentColor;stroke-opacity:1;stroke-dasharray:none;opacity:1\"\n       id=\"path1\"\n       cx=\"64\"\n       cy=\"64\"\n       r=\"56.554558\" />\n    <path\n       style=\"opacity:0.44;fill:currentColor;fill-opacity:1;stroke:none;stroke-width:0;stroke-linecap:round;stroke-dasharray:none;stroke-opacity:1;paint-order:markers stroke fill\"\n       id=\"path1-6\"\n       d=\"M -7.4454422,64 A 56.554558,56.554558 0 0 1 -64,120.55456 V 64 Z\"\n       transform=\"rotate(-90)\" />\n    <path\n       style=\"fill:none;fill-opacity:1;stroke:currentColor;stroke-width:7;stroke-linecap:round;stroke-dasharray:none;stroke-opacity:1;paint-order:markers stroke fill;opacity:1\"\n       d=\"M 64,7.4454422 V 120.55456\"\n       id=\"path2\" />\n    <path\n       style=\"fill:none;fill-opacity:1;stroke:currentColor;stroke-width:7;stroke-linecap:round;stroke-dasharray:none;stroke-opacity:1;paint-order:markers stroke fill;opacity:1\"\n       d=\"M 120.55456,64 H 7.4454422\"\n       id=\"path2-4\" />\n    <path\n       style=\"fill:none;fill-opacity:1;stroke:currentColor;stroke-width:7;stroke-linecap:round;stroke-dasharray:none;stroke-opacity:1;paint-order:markers stroke fill;opacity:1\"\n       d=\"M 112.97577,35.723825 64.000001,64\"\n       id=\"path2-4-6\" />\n    <path\n       style=\"fill:none;fill-opacity:1;stroke:currentColor;stroke-width:7;stroke-linecap:round;stroke-dasharray:none;stroke-opacity:1;paint-order:markers stroke fill;opacity:1\"\n       d=\"M 92.276173,15.024229 64.000001,64\"\n       id=\"path2-4-6-8\" />\n  </g>" },
  "close": { viewBox: "0 0 128 128", inner: "<defs>\n    <style>\n      .cls-1 {\n        fill: currentColor;\n        stroke-width: 0px;\n      }\n    </style>\n  </defs>\n  <polygon id=\"icon\" class=\"cls-1\" fill=\"currentColor\" points=\"14.5 23 28.6 20.2 64 55.5 99.4 20.2 113.5 23 72.5 64 113.5 105 99.4 107.8 64 72.5 28.6 107.8 14.5 105 55.5 64 14.5 23\"/>" },
  "dots": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\" transform=\"matrix(0.5,0,0,0.5,0,0) rotate(90 128 128)\">\n      <g transform=\"matrix(1,0,0,1,-2.84862,-15.156)\">\n         <circle cx=\"130.849\" cy=\"47.064\" r=\"31.908\"/>\n      </g>\n      <g transform=\"matrix(1,0,0,1,-2.84862,177.028)\">\n         <circle cx=\"130.849\" cy=\"47.064\" r=\"31.908\"/>\n      </g>\n      <g transform=\"matrix(1,0,0,1,-2.84862,80.9358)\">\n         <circle cx=\"130.849\" cy=\"47.064\" r=\"31.908\"/>\n      </g>\n   </g>" },
  "drag": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\">\n    <g transform=\"matrix(5,0,0,5,-124,-143)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    <g transform=\"matrix(5,0,0,5,-92,-143)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    <g transform=\"matrix(5,0,0,5,-124,-111)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    <g transform=\"matrix(5,0,0,5,-92,-111)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    <g transform=\"matrix(5,0,0,5,-124,-79)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    <g transform=\"matrix(5,0,0,5,-92,-79)\">\n        <path d=\"M32,37L34,37L36,35L36,33L34,33L32,35L32,37Z\"/>\n    </g>\n    </g>" },
  "dragger": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\">\n    <polygon points=\"12.1 80 128 63.7 120.5 82.2 14.5 97.1 12.1 80\"/>\n    <polygon points=\"115.9 48 0 64.3 7.5 45.8 113.5 30.9 115.9 48\"/>\n  </g>" },
  "fox": { viewBox: "0 0 128 128", inner: "<g fill=\"currentColor\" id=\"icon\">\n\t<polygon  points=\"64,128 15.4,53.2 21.1,52.9 56.9,110.6 61.5,105.3 61.5,80.1 64,71.8 66.6,80.1 66.6,105.3 72,108.5 \n\t\t105.8,52.9 112.6,53.3 \t\"/>\n\t<polygon  points=\"21.1,52.9 47.2,49 59.4,66.3 47.5,28.5 41.3,29.7 31,0 15.4,53.2 \t\"/>\n\t<polygon  points=\"106.9,52.9 80.8,51 68.6,66.3 80.5,28.5 86.7,29.7 97,0 112.6,53.2 \t\"/>\n\t<polyline  points=\"63.9,70.1 83.7,7 68,41.7 64,25.2 59.8,44.8 44.1,7 \t\"/>\n\t<ellipse  cx=\"45.4\" cy=\"70.3\" rx=\"4.1\" ry=\"4.7\"/>\n\t<ellipse  cx=\"84.1\" cy=\"70.1\" rx=\"4.1\" ry=\"4.7\"/>\n</g>" },
  "search": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\">\n    <polygon points=\"91.8 84.9 128 123.4 108.6 128 79.2 96.8 91.8 84.9\"/>\n    <path d=\"M55.1,111.1C24.4,111.1-.5,86.2-.5,55.5S24.4,0,55.1,0s55.5,24.9,55.5,55.5-24.9,55.5-55.5,55.5ZM55.1,14c-22.9,0-41.5,18.6-41.5,41.5s18.6,41.5,41.5,41.5,41.5-18.6,41.5-41.5S78,14,55.1,14Z\"/>\n  </g>" },
};

export function getIcon(noun: CommunityNoun | (string & {})): IconEntry | undefined {
  return _registry[noun as CommunityNoun];
}

export function getNouns(): CommunityNoun[] {
  return Object.keys(_registry) as CommunityNoun[];
}
