// @generated by scripts/generate-icon-registry.mjs — DO NOT EDIT

export type CommunityNoun =
  | "fox"
  | "search";

export interface IconEntry {
  inner: string;
  viewBox: string;
}

const _registry: Record<CommunityNoun, IconEntry> = {
  "fox": { viewBox: "0 0 128 128", inner: "<g fill=\"currentColor\" id=\"icon\">\n\t<polygon  points=\"64,128 15.4,53.2 21.1,52.9 56.9,110.6 61.5,105.3 61.5,80.1 64,71.8 66.6,80.1 66.6,105.3 72,108.5 \n\t\t105.8,52.9 112.6,53.3 \t\"/>\n\t<polygon  points=\"21.1,52.9 47.2,49 59.4,66.3 47.5,28.5 41.3,29.7 31,0 15.4,53.2 \t\"/>\n\t<polygon  points=\"106.9,52.9 80.8,51 68.6,66.3 80.5,28.5 86.7,29.7 97,0 112.6,53.2 \t\"/>\n\t<polyline  points=\"63.9,70.1 83.7,7 68,41.7 64,25.2 59.8,44.8 44.1,7 \t\"/>\n\t<ellipse  cx=\"45.4\" cy=\"70.3\" rx=\"4.1\" ry=\"4.7\"/>\n\t<ellipse  cx=\"84.1\" cy=\"70.1\" rx=\"4.1\" ry=\"4.7\"/>\n</g>" },
  "search": { viewBox: "0 0 128 128", inner: "<g id=\"icon\" fill=\"currentColor\">\n    <polygon points=\"91.8 84.9 128 123.4 108.6 128 79.2 96.8 91.8 84.9\"/>\n    <path d=\"M55.1,111.1C24.4,111.1-.5,86.2-.5,55.5S24.4,0,55.1,0s55.5,24.9,55.5,55.5-24.9,55.5-55.5,55.5ZM55.1,14c-22.9,0-41.5,18.6-41.5,41.5s18.6,41.5,41.5,41.5,41.5-18.6,41.5-41.5S78,14,55.1,14Z\"/>\n  </g>" },
};

export function getIcon(noun: CommunityNoun | (string & {})): IconEntry | undefined {
  return _registry[noun as CommunityNoun];
}

export function getNouns(): CommunityNoun[] {
  return Object.keys(_registry) as CommunityNoun[];
}
