/**
 * Resolves placeholders, validates relationships between seed documents,
 * and derives the tag index without network access or credentials.
 * `reset-and-seed.ts` performs storage and database I/O; `seed-model.test.ts`
 * tests validation directly.
 */
import {
  ACCOUNTS_COLLECTION_NAME,
  type Account,
  parseAccount,
} from 'src/schemas/AccountSchema';
import { type AppMeta, AppMetaSchema } from 'src/schemas/AppMetaSchema';
import { type Channel, parseChannel } from 'src/schemas/ChannelSchema';
import {
  PAGES_COLLECTION_NAME,
  type Page,
  parsePage,
} from 'src/schemas/PageSchema';
import {
  PROFILES_COLLECTION_NAME,
  type Profile,
  parseProfile,
} from 'src/schemas/ProfileSchema';
import {
  parseReply,
  REPLIES_COLLECTION,
  type Reply,
} from 'src/schemas/ReplySchema';
import {
  SITES_COLLECTION_NAME,
  type Site,
  SiteSchema,
} from 'src/schemas/SiteSchema';
import {
  TAG_FIRESTORE_COLLECTION,
  type Tag,
  TagSchema,
} from 'src/schemas/TagSchema';
import {
  parseThread,
  THREADS_COLLECTION_NAME,
  type Thread,
} from 'src/schemas/ThreadSchema';
import { toTagData } from 'src/utils/shared/toTagData';

export {
  ACCOUNTS_COLLECTION_NAME,
  PROFILES_COLLECTION_NAME,
  SITES_COLLECTION_NAME,
  PAGES_COLLECTION_NAME,
  THREADS_COLLECTION_NAME,
  REPLIES_COLLECTION,
  TAG_FIRESTORE_COLLECTION,
};

// biome-ignore lint/suspicious/noExplicitAny: seed documents are untyped JSON validated by application schemas.
export type SeedDoc = Record<string, any>;

export interface RawSeed {
  account: SeedDoc;
  profiles: SeedDoc;
  sites: SeedDoc;
  pages: SeedDoc;
  threads: SeedDoc;
  replies: SeedDoc;
  meta: SeedDoc;
}

/** Resolved values for user UIDs, asset URLs, and current timestamp placeholders. */
export interface PlaceholderMap {
  uidByPlaceholder: Record<string, string>;
  assetUrlMap: Map<string, string>;
  now: number;
}

export interface SeedModel {
  accounts: Record<string, Account>;
  profiles: Record<string, Profile>;
  sites: Record<string, Site>;
  /** Keyed by compound `siteKey/pageKey` identifiers from `pages.json`. */
  pages: Record<string, Page>;
  threads: Record<string, Thread>;
  /** Keyed by compound `threadKey/replyKey` identifiers from `replies.json`. */
  replies: Record<string, Reply>;
  channels: Channel[];
  appMeta: AppMeta;
  /** Keyed by Firestore tag document identifiers generated by `toTagData`. */
  tags: Record<string, Tag>;
}

/**
 * Resolves a placeholder string against user UIDs, asset URLs, or current timestamps.
 *
 * Every string starting with `@` represents a placeholder. Unresolved `@` strings
 * throw an error before database writes occur.
 */
export function resolveString(
  value: string,
  { uidByPlaceholder, assetUrlMap, now }: PlaceholderMap,
): string | number {
  if (value in uidByPlaceholder) return uidByPlaceholder[value];
  if (value === '@now') return now;
  const assetMatch = value.match(/^@asset:(.+)$/);
  if (assetMatch) {
    const url = assetUrlMap.get(assetMatch[1]);
    if (!url) {
      throw new Error(`No uploaded asset found for ${value}`);
    }
    return url;
  }
  // A placeholder is a bare `@name`. A fediverse handle such as
  // `@koekayttaja@pelilauta.social` carries a second `@` and a dot, and is
  // content, not a placeholder.
  if (/^@[A-Za-z][A-Za-z0-9]*$/.test(value)) {
    throw new Error(`Unresolvable placeholder "${value}"`);
  }
  return value;
}

export function resolveDeep(value: unknown, ctx: PlaceholderMap): unknown {
  if (typeof value === 'string') return resolveString(value, ctx);
  if (Array.isArray(value))
    return value.map((entry) => resolveDeep(entry, ctx));
  if (value && typeof value === 'object') {
    const out: SeedDoc = {};
    for (const [key, entry] of Object.entries(value as SeedDoc)) {
      out[resolveString(key, ctx) as string] = resolveDeep(entry, ctx);
    }
    return out;
  }
  return value;
}

/**
 * Traverses a seed document to collect `@asset:<filename>` references and optional `storagePath` destinations.
 *
 * An explicit `storagePath` overrides default upload destinations regardless of traversal order.
 */
export function collectAssetRefs(
  value: unknown,
  refs: Map<string, string | undefined>,
): void {
  if (Array.isArray(value)) {
    for (const entry of value) collectAssetRefs(entry, refs);
    return;
  }
  if (value && typeof value === 'object') {
    const obj = value as SeedDoc;
    const storagePath =
      typeof obj.storagePath === 'string' ? obj.storagePath : undefined;
    for (const entry of Object.values(obj)) {
      if (typeof entry === 'string') {
        const match = entry.match(/^@asset:(.+)$/);
        if (match) {
          const filename = match[1];
          if (storagePath || !refs.has(filename)) {
            refs.set(filename, storagePath ?? refs.get(filename));
          }
        }
      }
      collectAssetRefs(entry, refs);
    }
  }
}

function splitCompoundKey(
  compoundKey: string,
  description: string,
): [string, string] {
  const parts = compoundKey.split('/');
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(
      `${description} "${compoundKey}" must be a compound key of exactly two non-empty parts`,
    );
  }
  return [parts[0], parts[1]];
}

/**
 * Resolves placeholders, validates seed documents, and derives the tag index.
 * Throws when a document reference or count fails validation.
 */
export function buildSeedModel(raw: RawSeed, ctx: PlaceholderMap): SeedModel {
  const accountsRaw = resolveDeep(raw.account, ctx) as SeedDoc;
  const accounts: SeedModel['accounts'] = {};
  for (const [uid, data] of Object.entries(accountsRaw)) {
    accounts[uid] = parseAccount(data, uid);
  }

  const profilesRaw = resolveDeep(raw.profiles, ctx) as SeedDoc;
  const profiles: SeedModel['profiles'] = {};
  for (const [uid, data] of Object.entries(profilesRaw)) {
    profiles[uid] = parseProfile(data, uid);
  }

  const sitesRaw = resolveDeep(raw.sites, ctx) as SeedDoc;
  const sites: SeedModel['sites'] = {};
  for (const [key, data] of Object.entries(sitesRaw)) {
    sites[key] = SiteSchema.parse(data);
  }

  const pagesRaw = resolveDeep(raw.pages, ctx) as SeedDoc;
  const pages: SeedModel['pages'] = {};
  for (const [compoundKey, data] of Object.entries(pagesRaw)) {
    const [siteKey, pageKey] = splitCompoundKey(compoundKey, 'Page key');
    if (!sites[siteKey]) {
      throw new Error(
        `Page "${compoundKey}" references unknown site "${siteKey}"`,
      );
    }
    pages[compoundKey] = parsePage(data, pageKey, siteKey);
  }

  const threadsRaw = resolveDeep(raw.threads, ctx) as SeedDoc;
  const threads: SeedModel['threads'] = {};
  for (const [key, data] of Object.entries(threadsRaw)) {
    threads[key] = parseThread(data, key);
  }

  const repliesRaw = resolveDeep(raw.replies, ctx) as SeedDoc;
  const replies: SeedModel['replies'] = {};
  for (const [compoundKey, data] of Object.entries(repliesRaw)) {
    const [threadKey, replyKey] = splitCompoundKey(compoundKey, 'Reply key');
    if (!threads[threadKey]) {
      throw new Error(
        `Reply "${compoundKey}" references unknown thread "${threadKey}"`,
      );
    }
    replies[compoundKey] = parseReply(data, replyKey, threadKey);
  }

  const replyCountByThread = new Map<string, number>();
  for (const compoundKey of Object.keys(replies)) {
    const [threadKey] = compoundKey.split('/');
    replyCountByThread.set(
      threadKey,
      (replyCountByThread.get(threadKey) ?? 0) + 1,
    );
  }
  for (const [threadKey, thread] of Object.entries(threads)) {
    const actual = replyCountByThread.get(threadKey) ?? 0;
    const declared = thread.replyCount ?? 0;
    if (actual !== declared) {
      throw new Error(
        `Thread "${threadKey}" declares replyCount ${declared} but the seed has ${actual}`,
      );
    }
  }

  const metaRaw = resolveDeep(raw.meta, ctx) as SeedDoc;
  const appMeta = AppMetaSchema.parse(metaRaw.pelilauta);
  const channels = (metaRaw.threads.topics as SeedDoc[]).map((topic) =>
    parseChannel(topic),
  );

  const threadCountByChannel = new Map<string, number>();
  for (const thread of Object.values(threads)) {
    threadCountByChannel.set(
      thread.channel,
      (threadCountByChannel.get(thread.channel) ?? 0) + 1,
    );
  }
  for (const channel of channels) {
    const actual = threadCountByChannel.get(channel.slug) ?? 0;
    if (actual !== channel.threadCount) {
      throw new Error(
        `Channel "${channel.slug}" declares threadCount ${channel.threadCount} but the seed has ${actual}`,
      );
    }
  }

  // Generates tag documents for public threads and visible pages.
  const tags: SeedModel['tags'] = {};
  for (const [threadKey, thread] of Object.entries(threads)) {
    if (thread.public && thread.tags && thread.tags.length > 0) {
      tags[threadKey] = TagSchema.parse(
        toTagData(thread, threadKey, 'thread', thread.flowTime),
      );
    }
  }
  for (const [compoundKey, page] of Object.entries(pages)) {
    const [siteKey] = compoundKey.split('/');
    const site = sites[siteKey];
    if (site && !site.hidden && page.tags && page.tags.length > 0) {
      tags[page.key] = TagSchema.parse(
        toTagData(page, `${siteKey}/${page.key}`, 'page', page.flowTime),
      );
    }
  }

  return {
    accounts,
    profiles,
    sites,
    pages,
    threads,
    replies,
    channels,
    appMeta,
    tags,
  };
}
